#!/bin/bash

# this function prepares couchdb for beerlog

# erase previously existing db
curl -X DELETE http://127.0.0.1:5984/beers
curl -X PUT http://127.0.0.1:5984/beers
#curl -X PUT http://127.0.0.1:5984/beers/_design/index -d'{"_id":"_design/index","language":"javascript","views":{"index":{"map":"function(doc) {  emit(doc._id,doc.brewery);}"}}}'
curl -X POST http://127.0.0.1:5984/beers/_bulk_docs -H "Content-Type: application/json" -d'{"docs":[{"_id":"(512) ALT","brewery":"(512) Brewing Company"},{"_id":"(512) Bruin","brewery":"(512) Brewing Company"},{"_id":"(512) ONE","brewery":"(512) Brewing Company"},{"_id":"(512) Pecan Porter","brewery":"(512) Brewing Company"},{"_id":"(512) TWO","brewery":"(512) Brewing Company"},{"_id":"(512) Whiskey Barrel Aged Double Pecan Porter","brewery":"(512) Brewing Company"},{"_id":"Back in Black","brewery":"21st Amendment Brewing"},{"_id":"Brew Free! or Die","brewery":"21st Amendment Brewing"},{"_id":"Fireside Chat","brewery":"21st Amendment Brewing"},{"_id":"Hell or High Watermelon","brewery":"21st Amendment Brewing"},{"_id":"Monks Blood","brewery":"21st Amendment Brewing"},{"_id":"Leffe Dark","brewery":"Abbaye de Leffe"},{"_id":"Leffe Blonde","brewery":"Abbaye de Leffe"},{"_id":"Leffe Triple","brewery":"Abbaye de Leffe"},{"_id":"Leffe Radieuse","brewery":"Abbaye de Leffe"},{"_id":"Leffe 9°","brewery":"Abbaye de Leffe"},{"_id":"Abbey Ale","brewery":"Abita Brewing Company"},{"_id":"Amber","brewery":"Abita Brewing Company"},{"_id":"Andygator","brewery":"Abita Brewing Company"},{"_id":"Bock","brewery":"Abita Brewing Company"},{"_id":"Christmas Ale","brewery":"Abita Brewing Company"},{"_id":"Fall Fest","brewery":"Abita Brewing Company"},{"_id":"Golden","brewery":"Abita Brewing Company"},{"_id":"Jockamo","brewery":"Abita Brewing Company"},{"_id":"Light","brewery":"Abita Brewing Company"},{"_id":"Pecan","brewery":"Abita Brewing Company"},{"_id":"Purple Haze","brewery":"Abita Brewing Company"},{"_id":"Red Ale","brewery":"Abita Brewing Company"},{"_id":"Restoration","brewery":"Abita Brewing Company"},{"_id":"Satsuma","brewery":"Abita Brewing Company"},{"_id":"Save Our Shore","brewery":"Abita Brewing Company"},{"_id":"Strawberry","brewery":"Abita Brewing Company"},{"_id":"Turbodog","brewery":"Abita Brewing Company"},{"_id":"Wheat","brewery":"Abita Brewing Company"},{"_id":"Amber","brewery":"Alaskan Brewing Company"},{"_id":"IPA","brewery":"Alaskan Brewing Company"},{"_id":"Pale","brewery":"Alaskan Brewing Company"},{"_id":"Smoked Porter","brewery":"Alaskan Brewing Company"},{"_id":"Stout","brewery":"Alaskan Brewing Company"},{"_id":"Summer Ale","brewery":"Alaskan Brewing Company"},{"_id":"White","brewery":"Alaskan Brewing Company"},{"_id":"Winter Ale","brewery":"Alaskan Brewing Company"},{"_id":"Ambergeddon","brewery":"Ale Asylum"},{"_id":"Contorter Porter","brewery":"Ale Asylum"},{"_id":"Hopalicious","brewery":"Ale Asylum"},{"_id":"Madtown Nutbrown","brewery":"Ale Asylum"},{"_id":"Anvil ESB","brewery":"AleSmith"},{"_id":"Evil Dead Red","brewery":"AleSmith"},{"_id":"Grand Cru","brewery":"AleSmith"},{"_id":"Horny Devil","brewery":"AleSmith"}]}'
couchapp push . http://127.0.0.1:5984/beers
